// GENERATED by `npm run gen:api` from the OpenAPI of dino-autofocus 0.0.1. Do not edit by hand.

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State
         * @description The engine's snapshot: positions, lights, running operations, session, sample...
         */
        get: operations["state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Permissions
         * @description `?ops=a,b,c` -> may I do each now, and if not, why. Engine operations and the stops
         *     come from the engine's `check()` with login, loopback, role and D13 on top; the
         *     session actions and `submit_question` from the T-018 permissions plus loopback.
         */
        get: operations["permissions_api_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commands
         * @description Hand a command to the engine. Whether it runs is reported by events.
         */
        post: operations["commands_api_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Shutdown
         * @description Stop the engine (lights off with readback, abort, finish records), then exit. The
         *     launcher calls this before any hard kill. Microscope PC only, no D13 exception.
         */
        post: operations["shutdown_api_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            detail: components["schemas"]["RefusalDetail"];
        };
        /** AuraState */
        AuraState: {
            /**
             * State
             * @default unknown
             */
            state: string;
            /** Lines */
            lines?: {
                [key: string]: number | null;
            };
        } & {
            [key: string]: unknown;
        };
        /** CommandAccepted */
        CommandAccepted: {
            /** Op Id */
            op_id: string;
        };
        /**
         * CommandIn
         * @description A command for the engine, as the browser sends it. `start` names an operation in `op`
         *     with its `args`; `abort`, `confirm` and `update` name the running operation by `op_id`;
         *     `approve` / `reject` name a proposal by `op_id`; `lights_off` pre-empts anything. Any
         *     other field is refused (422): the server sets the rest (see SERVER_STAMPED).
         */
        CommandIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "start" | "abort" | "confirm" | "lights_off" | "update" | "approve" | "reject";
            /**
             * Op
             * @default
             */
            op: string;
            /**
             * Op Id
             * @default
             */
            op_id: string;
            /** Args */
            args?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareState */
        HardwareState: {
            /** Profile */
            profile?: {
                [key: string]: unknown;
            } | null;
            /** Profile Path */
            profile_path?: string | null;
            /** Gates */
            gates?: {
                [key: string]: unknown;
            };
            /** Last Status */
            last_status?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Engine */
            engine: string;
            /** Remote View */
            remote_view: boolean;
            /** Remote Abort */
            remote_abort: boolean;
        };
        /** LampState */
        LampState: {
            /**
             * State
             * @default unknown
             */
            state: string;
            /** Intensity */
            intensity?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Lights
         * @description The one light shape (light_changed, snapshot, records).
         */
        Lights: {
            dialamp?: components["schemas"]["LampState"];
            aura?: components["schemas"]["AuraState"];
            /** Verified */
            verified?: boolean | null;
            /** Records */
            records?: {
                [key: string]: unknown;
            }[];
            /** Error */
            error?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** OpSummary */
        OpSummary: {
            /** Op Id */
            op_id: string;
            /** Op */
            op: string;
            /** State */
            state: string;
            /**
             * Origin
             * @default human
             */
            origin: string;
            /** User Id */
            user_id?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Proposal Id */
            proposal_id?: string | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Confirmed By */
            confirmed_by?: string | null;
            /** Confirmed At */
            confirmed_at?: number | null;
            /** Record Prefix */
            record_prefix?: string | null;
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /**
             * Why
             * @default
             */
            why: string;
            /** Last Progress */
            last_progress?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * PermissionOut
         * @description One entry of `GET /api/permissions`: may the asking person do this now, and if not,
         *     why (`reason`, shown before the click) and the refusal `code` when the server says no
         *     (login_required, locked, remote_view, role); None when the engine says no.
         */
        PermissionOut: {
            /** Allowed */
            allowed: boolean;
            /** Reason */
            reason?: string | null;
            /** Code */
            code?: string | null;
        };
        /**
         * Positions
         * @description Stage readback in um; None where the read failed, with the reason in `errors`.
         */
        Positions: {
            /** X Um */
            x_um?: number | null;
            /** Y Um */
            y_um?: number | null;
            /** Z Um */
            z_um?: number | null;
            /** Piezo Um */
            piezo_um?: {
                [key: string]: number;
            };
            /** Errors */
            errors?: {
                [key: string]: string;
            };
            /** T */
            t?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RefusalDetail
         * @description Why the server said no. `code` is also in the `X-DinoAF-Refusal` header. Codes:
         *     login_required (401), locked (423), remote_view (403; the web client turns read-only
         *     on this one only), foreign_origin, map_route, role (403), refused (400, the engine said
         *     no), shutting_down (503), shutdown_failed (500).
         */
        RefusalDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** SampleRef */
        SampleRef: {
            /** Sample Id */
            sample_id?: string | null;
            /**
             * Reserved
             * @default false
             */
            reserved: boolean;
            /** Session Id */
            session_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SessionRef */
        SessionRef: {
            /** Session Id */
            session_id?: string | null;
            /** Started At */
            started_at?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ShutdownAccepted
         * @description The engine has stopped (abort, lights off with readback, records finished); the server
         *     exits next. `already` is true when another exit path had stopped the engine first.
         */
        ShutdownAccepted: {
            /** Reason */
            reason: string;
            /** Already */
            already: boolean;
        };
        /** ShutdownIn */
        ShutdownIn: {
            /**
             * Reason
             * @default api
             */
            reason: string;
        };
        /**
         * Snapshot
         * @description The engine's current state.
         */
        Snapshot: {
            positions?: components["schemas"]["Positions"] | null;
            lights?: components["schemas"]["Lights"] | null;
            /** Owner */
            owner?: string | null;
            /** Running */
            running?: components["schemas"]["OpSummary"][];
            /** Proposals */
            proposals?: components["schemas"]["OpSummary"][];
            /** Pending Confirms */
            pending_confirms?: {
                [key: string]: unknown;
            }[];
            /** Awaiting Return */
            awaiting_return?: {
                [key: string]: unknown;
            } | null;
            session?: components["schemas"]["SessionRef"] | null;
            sample?: components["schemas"]["SampleRef"] | null;
            /** Last Shutdown Lights */
            last_shutdown_lights?: {
                [key: string]: unknown;
            } | null;
            /** Unclean Shutdown */
            unclean_shutdown?: {
                [key: string]: unknown;
            } | null;
            hardware?: components["schemas"]["HardwareState"] | null;
            /** Stream */
            stream?: {
                [key: string]: unknown;
            } | null;
            /** Recent */
            recent?: components["schemas"]["OpSummary"][];
            /** Operations */
            operations?: string[];
            /** Permissions */
            permissions?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * EventOut
         * @description `user_id` / `session_id` are the operation's (rule 12); None for engine-wide events.
         */
        EventOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "planned" | "preflight_ok" | "preflight_failed" | "started" | "progress" | "frame_ready" | "reading" | "finished" | "aborted" | "error" | "position" | "light_changed" | "property_set" | "motion" | "confirm_required" | "confirmed" | "proposed" | "approved" | "rejected" | "refused" | "updated" | "map_changed" | "sample_opened" | "objective" | "session_changed" | "log";
            /**
             * Op Id
             * @default
             */
            op_id: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** T */
            t: number;
            /**
             * User Id
             * @default null
             */
            user_id: string | null;
            /**
             * Session Id
             * @default null
             */
            session_id: string | null;
        };
        /**
         * WsAccepted
         * @description `/ws/events`, server -> client: reply to a `WsCommand`.
         */
        WsAccepted: {
            /**
             * Type
             * @default accepted
             * @constant
             */
            type: "accepted";
            /** Op Id */
            op_id: string;
        };
        /**
         * WsCommand
         * @description `/ws/events`, client -> server. Accepted only from the microscope PC (loopback).
         */
        WsCommand: {
            /**
             * Type
             * @default command
             * @constant
             */
            type: "command";
            command: components["schemas"]["CommandIn"];
        };
        /**
         * WsError
         * @description `/ws/*`, server -> client: a refused or malformed message. `status` and `code` follow
         *     the REST refusals (401 login_required, 423 locked, 403 remote_view and others, 400
         *     refused by the engine, 422 bad message, 503 shutting_down). A 401/423 on connect is
         *     followed by a close.
         */
        WsError: {
            /**
             * Type
             * @default error
             * @constant
             */
            type: "error";
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /**
             * Code
             * @default null
             */
            code: string | null;
        };
        /**
         * WsEvent
         * @description `/ws/events`, server -> client.
         */
        WsEvent: {
            /**
             * Type
             * @default event
             * @constant
             */
            type: "event";
            event: components["schemas"]["EventOut"];
        };
        /**
         * WsFrame
         * @description `/ws/frames`, server -> client. Always sent as a text message immediately followed by
         *     one binary message holding the JPEG (`jpeg_bytes` long). Pixel values were mapped
         *     linearly from `display_min..display_max` (raw counts) to 0..255.
         */
        WsFrame: {
            /**
             * Type
             * @default frame
             * @constant
             */
            type: "frame";
            /** Seq */
            seq: number;
            /** T */
            t: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Binning */
            binning: number;
            /** Source Width */
            source_width: number;
            /** Source Height */
            source_height: number;
            /** Display Min */
            display_min: number;
            /** Display Max */
            display_max: number;
            /** Jpeg Bytes */
            jpeg_bytes: number;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    permissions_api_permissions_get: {
        parameters: {
            query?: {
                ops?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["PermissionOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commands_api_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Locked */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    shutdown_api_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShutdownIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShutdownAccepted"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
