// GENERATED by `npm run gen:api` from the OpenAPI of dino-autofocus 0.0.1. Do not edit by hand.

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State
         * @description The engine's snapshot: positions, lights, running operation.
         */
        get: operations["state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commands
         * @description Hand a command to the engine. Whether it runs is reported by events.
         */
        post: operations["commands_api_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Shutdown
         * @description Stop the engine (lights off with readback, abort, finish records), then exit. The
         *     launcher calls this before any hard kill. Microscope PC only, no D13 exception.
         */
        post: operations["shutdown_api_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            /** Detail */
            detail: string;
        };
        /** CommandAccepted */
        CommandAccepted: {
            /** Op Id */
            op_id: string;
        };
        /**
         * CommandIn
         * @description A command for the engine. `start` names an operation in `op` with its `args`; `abort`
         *     and `confirm` name the running operation by `op_id`; `lights_off` pre-empts anything.
         *     An `assistant` command is a proposal until a human confirms it.
         */
        CommandIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "start" | "abort" | "confirm" | "lights_off";
            /**
             * Op
             * @default
             */
            op: string;
            /**
             * Op Id
             * @default
             */
            op_id: string;
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /**
             * Origin
             * @default human
             * @enum {string}
             */
            origin: "human" | "assistant";
            /** Session Id */
            session_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Engine */
            engine: string;
            /** Remote View */
            remote_view: boolean;
            /** Remote Abort */
            remote_abort: boolean;
        };
        /**
         * ShutdownAccepted
         * @description The engine has stopped (abort, lights off with readback, records finished); the server
         *     exits next. `already` is true when another exit path had stopped the engine first.
         */
        ShutdownAccepted: {
            /** Reason */
            reason: string;
            /** Already */
            already: boolean;
        };
        /** ShutdownIn */
        ShutdownIn: {
            /**
             * Reason
             * @default api
             */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** EventOut */
        EventOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "planned" | "preflight_ok" | "preflight_failed" | "started" | "progress" | "frame_ready" | "reading" | "finished" | "aborted" | "error" | "position" | "light_changed" | "property_set" | "motion" | "confirm_required" | "confirmed" | "log";
            /**
             * Op Id
             * @default
             */
            op_id: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** T */
            t: number;
        };
        /**
         * WsAccepted
         * @description `/ws/events`, server -> client: reply to a `WsCommand`.
         */
        WsAccepted: {
            /**
             * Type
             * @default accepted
             * @constant
             */
            type: "accepted";
            /** Op Id */
            op_id: string;
        };
        /**
         * WsCommand
         * @description `/ws/events`, client -> server. Accepted only from the microscope PC (loopback).
         */
        WsCommand: {
            /**
             * Type
             * @default command
             * @constant
             */
            type: "command";
            command: components["schemas"]["CommandIn"];
        };
        /**
         * WsError
         * @description `/ws/events`, server -> client: a refused or malformed message. `status` follows HTTP
         *     (400 refused by the engine, 403 not allowed from here, 422 bad message,
         *     503 shutting down).
         */
        WsError: {
            /**
             * Type
             * @default error
             * @constant
             */
            type: "error";
            /** Status */
            status: number;
            /** Detail */
            detail: string;
        };
        /**
         * WsEvent
         * @description `/ws/events`, server -> client.
         */
        WsEvent: {
            /**
             * Type
             * @default event
             * @constant
             */
            type: "event";
            event: components["schemas"]["EventOut"];
        };
        /**
         * WsFrame
         * @description `/ws/frames`, server -> client. Always sent as a text message immediately followed by
         *     one binary message holding the JPEG (`jpeg_bytes` long). Pixel values were mapped
         *     linearly from `display_min..display_max` (raw counts) to 0..255.
         */
        WsFrame: {
            /**
             * Type
             * @default frame
             * @constant
             */
            type: "frame";
            /** Seq */
            seq: number;
            /** T */
            t: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Binning */
            binning: number;
            /** Source Width */
            source_width: number;
            /** Source Height */
            source_height: number;
            /** Display Min */
            display_min: number;
            /** Display Max */
            display_max: number;
            /** Jpeg Bytes */
            jpeg_bytes: number;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    commands_api_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shutdown_api_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShutdownIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShutdownAccepted"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
