// npm run gen:api -- regenerate src/api/schema.ts from the server's OpenAPI.
//
// The schema comes from `python -m dino_autofocus.server --dump-openapi PATH` (T-009), run
// through uv so it uses the repo's environment. The output is generated: do not edit it by
// hand, change the pydantic models on the server and run this again.
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..", "..");
const out = resolve(here, "..", "src", "api", "schema.ts");

// DINO_AF_OPENAPI_JSON=<file> uses an already dumped schema instead of running the server
// (e.g. from a branch whose server is not on main yet). Say so in the commit.
const given = process.env.DINO_AF_OPENAPI_JSON;
const dir = mkdtempSync(join(tmpdir(), "dino-af-openapi-"));
const specPath = given ? resolve(given) : join(dir, "openapi.json");
try {
  const run = given ? { status: 0 } : spawnSync(
    "uv",
    ["run", "python", "-m", "dino_autofocus.server", "--dump-openapi", specPath],
    // no shell: uv is an .exe on Windows too, and a shell would split a path with a space
    { cwd: repo, stdio: "inherit" },
  );
  if (run.status !== 0) {
    console.error(
      "gen:api: the server could not dump its OpenAPI schema " +
        "(is dino_autofocus.server with --dump-openapi on this branch? see T-009)",
    );
    process.exit(1);
  }
  const spec = JSON.parse(readFileSync(specPath, "utf8"));
  const ast = await openapiTS(spec);
  const source = spec.info ? `${spec.info.title} ${spec.info.version}` : "the server";
  const header =
    `// GENERATED by \`npm run gen:api\` from the OpenAPI of ${source}. Do not edit by hand.\n\n`;
  writeFileSync(out, header + astToString(ast));
  console.log(`gen:api: wrote ${out}`);
} finally {
  rmSync(dir, { recursive: true, force: true });
}
